/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import component.Item_People;
import event.EventMenuRight;
import event.PublicEvent;
import models.Room;
import net.miginfocom.swing.MigLayout;

import java.io.IOException;
import java.util.ArrayList;
import java.util.UUID;

/**
 *
 * @author RAVEN
 */
public class Menu_Right extends javax.swing.JPanel {
    public static ArrayList<String> users = new ArrayList<>();

    /**
     * Creates new form Menu_Left
     */
    public Menu_Right() {

        initComponents();
        menuList.setLayout(new MigLayout("fillx", "0[]0", "0[]0"));
        menuList.add(new Item_People("user"), "wrap");
        PublicEvent.getInstance().addEventMenuRight(new EventMenuRight() {
            @Override
            public void addUser(String user) {
                System.out.println(users.indexOf(user));
                int index = users.indexOf(user);
                if(index >= 0) {
                    users.remove(index);
                }else users.add(user);
                showUsers();
            }
        });
    }

    private void showUsers() {
        //  test data
        menuList.removeAll();
        users.forEach(user -> {
            menuList.add(new Item_People(user), "wrap");
        });
        refreshMenuList();
    }

    private void refreshMenuList() {
        menuList.repaint();
        menuList.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        input = new javax.swing.JTextField();
        createBtn = new javax.swing.JButton();
        menuList = new javax.swing.JLayeredPane();

        setBackground(new java.awt.Color(249, 249, 249));

        createBtn.setBackground(new java.awt.Color(204, 255, 255));
        createBtn.setText("Create room");
        createBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    createBtnActionPerformed(evt);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });

        javax.swing.GroupLayout menuListLayout = new javax.swing.GroupLayout(menuList);
        menuList.setLayout(menuListLayout);
        menuListLayout.setHorizontalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        menuListLayout.setVerticalGroup(
            menuListLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 555, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(menuList)
                    .addComponent(createBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(input, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(input, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(menuList)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(createBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void createBtnActionPerformed(java.awt.event.ActionEvent evt) throws IOException {//GEN-FIRST:event_createBtnActionPerformed
        String roomName = input.getText();
        if(!roomName.trim().isEmpty()) {
            UUID roomId = UUID.randomUUID();
            Room room = new Room(roomId.toString(),roomName, users);
            PublicEvent.getInstance().getEventMainChat().createRoom(room);
            menuList.removeAll();
            users = new ArrayList<>();
            input.setText("");
            refreshMenuList();
        }


    }//GEN-LAST:event_createBtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton createBtn;
    private javax.swing.JTextField input;
    private javax.swing.JLayeredPane menuList;
    // End of variables declaration//GEN-END:variables
}
